name: Build Dming4 Linux

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build amd64 Linux
    runs-on: ubuntu-22.04

    container:
      image: debian:10

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          apt update
          apt install -y \
            curl \
            git \
            file \
            build-essential \
            pkg-config \
            libwayland-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcursor-dev \
            libxfixes-dev \
            libegl1-mesa-dev \
            libvulkan-dev

      - name: Install Go
        run: |
          curl -LO https://go.dev/dl/go1.27.0.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.27.0.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Check environment
        run: |
          go version
          gcc --version
          pkg-config --version

      - name: Download modules
        run: |
          go mod download

      - name: Build
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64
        run: |
          go build \
            -trimpath \
            -ldflags="-s -w" \
            -o Dming4

      - name: Check binary
        run: |
          file Dming4
          ldd Dming4 || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Dming4-linux-amd64
          path: Dming4