name: Set EXE Icon

on:
  workflow_dispatch:
    inputs:
      exe_path:
        description: "EXE file path"
        required: true
        type: string

      icon_path:
        description: "ICO icon path"
        required: true
        type: string

jobs:
  set-icon:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install rcedit
        run: |
          npm install rcedit

      - name: Set EXE icon
        shell: pwsh
        run: |
          node -e "require('./node_modules/rcedit/lib/rcedit')('${{ inputs.exe_path }}', {icon:'${{ inputs.icon_path }}'}).then(()=>console.log('done')).catch(e=>{console.error(e);process.exit(1)})"

      - name: Upload modified EXE
        uses: actions/upload-artifact@v7
        with:
          name: exe-with-icon
          path: ${{ inputs.exe_path }}