name: Set EXE Icon

on:
  workflow_dispatch:
    inputs:
      exe_path:
        description: "exe路径"
        required: true
        type: string

      icon_path:
        description: "图标路径(.ico)"
        required: true
        type: string

jobs:
  set-icon:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install rcedit
        run: |
          npm install -g rcedit

      - name: Set EXE icon
        shell: pwsh
        run: |
          npx rcedit "${{ inputs.exe_path }}" --set-icon "${{ inputs.icon_path }}"

      - name: Upload modified EXE
        uses: actions/upload-artifact@v7
        with:
          name: exe-with-icon
          path: ${{ inputs.exe_path }}